### ISSUE TITLE
Firefox Nighlty Tab switching is not working correctly

### ISSUE THREAD

**Issue by Jac-Zac** [egovelox/mozeidon#3]
I'll prefix by saying that I know this is not really the intended use, but I have Firefox Nightly installed and I was wondering if there is a way to fix this problem. Because If I try to run it even with this: 

```bash
mozeidon tabs get --go-template '{{range .Items}}{{.WindowId}}:{{.Id}} {{.Url}} {{if .Pinned}}📌{{else}}🦊{{end}} {{"\u001b[38;5;109m"}} {{.Domain}}{{"\033[0m"}} {{.Title}}{{"\n"}}{{end}}' \ 
| fzf --ansi --with-nth 3.. --bind=enter:accept-non-empty \
| cut -d ' ' -f1 \
| xargs -n1 -I % sh -c 'mozeidon tabs switch % && open -a /Applications/Firefox\ Nightly.app'
```
I can't really change to the selected tab.
Indeed it changes focus to Firefox Nightly because of the open -a .. but It doesn't move me to the tab I selected even though I could correctly select the desired tab. If you know where in the code I could change things to solve it or have a possible solution it would be nice, otherwise no worries. Thanks in advance

**Comment by egovelox** [comment]
Hi !

I tried to reproduce that bug on my Mac,
 but I could not see any difference between 
 ``open -a firefox`` and ``open -a /Applications/Firefox\ Nightly.app``. 

To make your command work, I first had to :
- install the Firefox Nightly app
- close the Firefox app ( it cannot work with two firefox instances )
- open the Firefox Nightly app and install the firefox Mozeidon extension ( since I chose not to synchronize add-ons between my various firefox instances - I want to install extensions myself, on each instance - I only synchronize bookmarks, not addons )
- execute in my terminal the command you provided ( I tested by choosing various tabs )

So I tend to think that both editions are working for me, on both editions I can switch to the desired tab.

Maybe : 
using Activity Monitor 
you can try to kill the process ``mozeidon-native-app`` 
( another same process will restart automatically if your Firefox is running with a running Mozeidon extension )

**Comment by egovelox** [comment]
If needed, here are the details of my setup :

Firefox Nightly
128.0a1 (2024-06-07) (64 bits)

<img width="649" alt="Screenshot 2024-06-07 at 11 05 27 PM" src="https://github.com/egovelox/mozeidon/assets/56078155/b0833b47-55ff-4d24-aeb3-f0962f19ffce">

**Comment by egovelox** [comment]
If you cannot find why it's not working on your machine,
a further debug method would be
to run only
``
mozeidon tabs get --go-template '{{range .Items}}{{.WindowId}}:{{.Id}} {{.Url}} {{if .Pinned}}📌{{else}}🦊{{end}} {{"\u001b[38;5;109m"}} {{.Domain}}{{"\033[0m"}} {{.Title}}{{"\n"}}{{end}}'  | fzf --ansi --with-nth 3.. --bind=enter:accept-non-empty
``
and to select a tab with enter.
Then, you should see as output in your terminal
( of course depending on the tab you chose )
``
3:15 https://github.com/egovelox/mozeidon 🦊  github.com egovelox/mozeidon: Mozeidon is a CLI to handle Mozilla Firefox tabs and bookmarks.
``

And then, using ``3:15`` (where ``3`` is the returned window id, and ``15`` the tab id)  
run in your terminal
``mozeidon tabs switch 3:15``
and check that your firefox has switched to the desired tab.

?

**Comment by Jac-Zac** [comment]
Yeah sorry my fault, I'll explain

**Comment by Jac-Zac** [comment]
I tested it with Raycast and found it to give me an error so tried to look at the terminal command to do it, and fount that to not work since I didn't have firefox but only the nightly version so I changed the command and for some reason (also a bit of not so lucky testing on my part) I though it still wasn't working

**Comment by Jac-Zac** [comment]
The problem was I was always trying to switch to tabs in different firefox windows I had in different workspaces and thus never found it to do anything if not just focusing on the firefox windows in my workspace

**Comment by egovelox** [comment]
Alright, 
I know this mozeidon command is currently messing things up when various firefox instances are running.
Added that the windows switching on MacOS can also mess things up.

That's a limitation, I cannot change that for now...

I'm glad that you can resolve this issue !

**Comment by Jac-Zac** [comment]
So two things:

First of all do you think I can make it work with raycast ? Maybe I can modify something to call this open -a /Applications/Firefox\ Nightly.app instead of the default ? 

Actually you clarified the second point for me so no need

**Comment by Jac-Zac** [comment]
Really appreciate the work you have done though thanks 👍

**Comment by egovelox** [comment]
Thanks, I had a lot of fun to code this weird mozeidon thing, that I'm now using everyday !

Yeah, for Raycast, changing the default command should do the trick !

**Comment by Jac-Zac** [comment]
Ah oky my fault I didn't see that you could change that too from raycast. I was trying to find it in the code and just found: ```export const FIREFOX_OPEN_COMMAND = preferences.firefox;``` and exactly after that read the message. Thanks
